@echo off
set "SCRIPT_DIR=%~dp0"
echo Stopping All Services...
echo 1. Stopping Frontend...
call "%SCRIPT_DIR%stop_frontend.bat"
echo 2. Stopping Backend...
call "%SCRIPT_DIR%stop_server.bat"
echo All services stopped!
